# 作業

思考一下我們前面有提到圖片是矩陣，但維度可能會不一樣
例如灰階圖只有兩個維度，RGB 彩圖則有 3 個維度

假如今天我們把 RGB 3 個維度拆開來看會有甚麼不同的效果呢？

In [ ]:
import cv2
import numpy as np

img_path = '../img/lena.png'

# 以 BGR 三個 channel 的方式載入
img = cv2.imread(img_path, cv2.IMREAD_COLOR)

# 顯示圖片大小 (高 x 寬) 及 channel 數
print(img.shape)

# B
B = img[...,0]
# G
G = img[...,1]
# R
R = img[...,2]

print("顯示 Blue channel\n", B)
print("顯示 Green channel\n", G)
print("顯示 Red channel\n", R)

# 複製圖片並清除其他兩個 channel

blue = img.copy()
blue[:, :, 1] = 0
blue[:, :, 2] = 0
green = img.copy()
green[:, :, 0] = 0
green[:, :, 2] = 0
red = img.copy()
red[:, :, 0] = 0
red[:, :, 1] = 0

# 參考解答, 並將圖片合併顯示
img_concat = np.hstack((img[:, :, 0], img[:, :, 1], img[:, :, 2]))

while True:
    # 顯示 Blue
    cv2.imshow('Blue', blue)
    # 顯示 Green
    cv2.imshow('Green', green)
    # 顯示 Red
    cv2.imshow('Red', red)
    # 顯示解答
    cv2.imshow('bgr_split', img_concat)

    # 直到按下 ESC 鍵才會自動關閉視窗結束程式
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

(512, 512, 3)
顯示 Blue channel
 [[125 125 133 ... 122 110  90]
 [125 125 133 ... 122 110  90]
 [125 125 133 ... 122 110  90]
 ...
 [ 60  60  58 ...  84  76  79]
 [ 57  57  62 ...  79  81  81]
 [ 57  57  62 ...  79  81  81]]
顯示 Green channel
 [[137 137 137 ... 148 130  99]
 [137 137 137 ... 148 130  99]
 [137 137 137 ... 148 130  99]
 ...
 [ 18  18  27 ...  73  68  62]
 [ 22  22  32 ...  70  71  74]
 [ 22  22  32 ...  70  71  74]]
顯示 Red channel
 [[226 226 223 ... 230 221 200]
 [226 226 223 ... 230 221 200]
 [226 226 223 ... 230 221 200]
 ...
 [ 84  84  92 ... 173 172 177]
 [ 82  82  96 ... 179 181 185]
 [ 82  82  96 ... 179 181 185]]
